### ISSUE TITLE
建议将 ['myvs_26'] 这个字段 设定为先从secrets读取， 如果为null 则设定默认值

### ISSUE THREAD

**Issue by lingyan12** [yuzhi535/jkdk#10]
self.form2['myvs_26'] = '2' 
这个字段 我看直接设定的是 value=2   即：接种第二针，但是有可能已经接种第三针，可能造成数据误差。
建议将 ['myvs_26'] 这个字段 设定为先从secrets读取， 如果为null 则设定默认值2

**Comment by yuzhi535** [comment]
可以，已经添加

**Comment by yuzhi535** [comment]
README等到今晚看看都有啥值再更新😂

**Comment by lingyan12** [comment]
哈哈  好嘞，
