### ISSUE TITLE
请问如果要添加多个用户的话，secret怎么写呀

### ISSUE THREAD

**Issue by kiritoxie** [yuzhi535/jkdk#6]
( ¯•㉨•¯ )

**Comment by yuzhi535** [comment]
你可以统一加，但是用特殊符号（我记得空格似乎就可以，因为学校要求的密码好像不能用空格）分开每个用户的配置。
比如把所有人的密码都放到password这个环境变量里面，然后用空格分开，然后在程序里面用split分开就行了。

**Comment by yuzhi535** [comment]
close
