### ISSUE TITLE
打不上卡

### ISSUE THREAD

**Issue by Liusu-s** [yuzhi535/jkdk#7]
由于如下原因，提交失败。请更正后重新提交。
请使用郑州大学官方软件平台上报个人健康状况。网址：https://jksb.v.zzu.edu.cn

大佬知道原因吗

**Comment by yuzhi535** [comment]
fun18字段每天变，得在hidden里面找一下对应值再提交

**Comment by yuzhi535** [comment]
我的代码里面的 jkdk.py 里面 jkdk2方法 就是获取fun18字段的值，你可以看看 @Liusu-s

**Comment by Liusu-s** [comment]
> 

收到，我有时候get的<input>不完全，只有ptopid和sid
