### ISSUE TITLE
请问是正在更新吗。Action里面无法运行

### ISSUE THREAD

**Issue by AlecMaxPro** [yuzhi535/jkdk#8]
Action里面提示“There are no workflow runs yet.”。     

感谢解答！

**Comment by yuzhi535** [comment]
奇怪，没遇到这种情况。请提供一下详细截图。

**Comment by AlecMaxPro** [comment]
<img width="1258" alt="截屏2022-04-14 13 52 06" src="https://user-images.githubusercontent.com/93110703/163322397-fc27b0cf-65a9-44c0-ae56-4afafd392a02.png">
我fork到我仓库后是这个情况

**Comment by yuzhi535** [comment]
你点 郑州大学健康打卡 是什么样子？

**Comment by AlecMaxPro** [comment]
<img width="1250" alt="截屏2022-04-14 14 59 15" src="https://user-images.githubusercontent.com/93110703/163331246-6a4a7eb9-813f-4c79-bce4-a9b61390bc77.png">
如图

**Comment by yuzhi535** [comment]
你把jkdk.yml稍微改一下试试，比如加个一行，加个空格之类的这种

**Comment by AlecMaxPro** [comment]
感谢大佬，已解决！
