### ISSUE TITLE
定位问题

### ISSUE THREAD

**Issue by cx99325** [yuzhi535/jkdk#9]
目前上报时的地理位置是会获取到学校外边的吗？请问有无影响呢。
今日打卡     上报时的地理位置：河南省郑州市二七区建设东路

**Comment by yuzhi535** [comment]
应该是填报的时候经纬度写错了，确实得改一下

**Comment by yuzhi535** [comment]
位置更新到厚德大道了，不知道网站会显示什么位置😓

**Comment by yuzhi535** [comment]
我这打卡显示为郑州大学主校区，应该好了吧

**Comment by cx99325** [comment]
定位已经没有问题了，是显示的主校区。但是还有一个问题是微信推送的消息总是显示打卡失败，但实际是成功的。见图片，1点时实际应该已成功。可否请大佬空闲了测试一下。
![微信图片_20220416192526](https://user-images.githubusercontent.com/66132100/163673184-436663b7-eff4-4ef0-867c-ef4d8ab509be.jpg)

**Comment by yuzhi535** [comment]
目前还有这个问题吗？最新的提交应该是已经更改过的了

**Comment by cx99325** [comment]
今日提交没有问题了，一切正常，感谢。
